controller:
  serviceType: NodePort
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  admin:
    username: admin
    password: admin123
  ingress:
    enabled: false
  servicePort: 8080
  targetPort: 8080
  nodePort: 30000

persistence:
  enabled: true
  size: 8Gi
  storageClass: "standard"

rbac:
  create: true

serviceAccount:
  create: true
  annotations: {}
